apiVersion: v1 
kind: Service 
metadata: 
  name: back-end
spec:
  type: ClusterIP #default so if you dont put nothing there it will assume clusterIP
  ports:
    - targetPort: 80
      port: 80
  selector:
    app: nginx
    type: back-end