apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: daemon
spec:
  selector: 
    matchLabels:
    app: myapp
  template:
    metadata:
      labels:
        app: myapp  
    spec:
      containers:
      - name: monitoring
        image: monitoring-agent  