apiVersion: v1
kind: Config

clusters:
- name: my-kube-playground
  cluster:  
    certificate-authority: http://proxy.example.org:3128
    server: https://k8s.example.org/k8s/clusters/c-xxyyzz
  name: development

users:
- name: my-kube-admin
  user:
    client-certification: admin.crt
    client-key: admin.key

contexts:
- name: my-kube-admin@my-kube-playground
  context:
    cluster: my-kube-playground
    user: my-kube-admin
    namespace: finance