apiVersion: apiserver.config.k8s.io/v1
clusters: 
- cluster: 
    certificate-authority: ca.crt
    server: https://kube-apiserver:6443
  name: kubernetes
kind: ConfigMap
users:
- name: kubernetes-admin
  user: 
    client-certificate: admin.crt
    client-key: admin.key
