apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort # type od service created (cluster IP, nodeport, loadbalancer)
  ports: # is an array the (-) on targetPort means its the first section of the array
    - targetPort: 80 # port of the service 
      port: 80 
      nodePort: 30008   # nodeport is allocated between number 300000 to 32767 if not specified
  selector: 
    app: myapp
    type: front-end