---
apiVersion: v1
kind: Pod
metadata:
  name: front-end
  labels:
    app: myapp
    type: front-end
spec:
  containers:
  - name: app
    image: redis
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: log-aggregator
    image: images.my-company.example/log-aggregator:v6
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"