---
apiVersion: v1 
kind: Pod
metadata: 
  name: nginx
  namespace: default
  labels: 
    app: nginx
    type: back-end
spec: 
  containers: 
  - name: nginx
    image: redis:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  
  
  # - name : busybox
  #   image: busybox
  #   resources:
  #     requests:
  #       memory: "64Mi"
  #       cpu: "250m"
  #     limits:
  #       memory: "128Mi"
  #       cpu: "500m"