apiVersion: v1 
kind: Pod 
metadata: 
  name: mypod-1
  labels:
    app: app12
    type: front-end
spec: 
  containers:
  - name: nginx-1 
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"