---
apiVersion: v1
kind: ReplicationController
metadata:                # replication Controller
  name: my-rc
  labels:
    app: myapp 
    type: front-end
spec:                     # replication Controller
  template: 
    metadata:             #  The pod
      name: nginx
      labels: 
        app: myapp
        type: front-end
    spec:                 # the Pod
      containers: 
      - name: nginx-controller
        image: nginx
  replicas: 3